# Generated by Django 3.0.8 on 2020-07-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200730_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedrooms',
            new_name='bedroom',
        ),
    ]
